# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CanvasDocker
                                 A QGIS plugin
 This plugin allows the QGIS map canvas to be undocked and maximized on a secondary screen, freeing up space in the main window for other dockable panels.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-09-16
        copyright            : (C) 2025 by Emiel Verstegen
        email                : emiel@verstegen.email
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load CanvasDocker class from file CanvasDocker.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .canvas_docker import CanvasDocker
    return CanvasDocker(iface)
